### PR TITLE
IID heuristic test ash

### PR DESCRIPTION
**Pull request by ashpace**

### CODE REVIEW

**Review by GiuseppeMascolo — COMMENTED** [review]
I commented one line. The main thing you missed is to change the main and add a call to the function

**Comment by ashpace** [comment]
@GiuseppeMascolo That will be done in a separate branch. It depends on where the for loop is being created. Currently, as this states, it is a function testing for IID using Heuristic Method. It is backtested. Later when we are building the upper hierarchy script, it will be implemented. However, please test the function as see if it is fulfilling its purpose. Later, when you approve, I will write a WiKi describing methodology and meaning of its outputs. To keep it short, each true in output means that it is IID by looking at one property. there are three properties: 

- is the mean of sample 2 in the confidence interval of mean of sample 1 

- is the sd of sample 2 in the confidence interval of sd of sample 1 

- is the lagged prices correlated with normal price series? 

three trues, therefore, means that it passed the heuristic test.

**Comment by GiuseppeMascolo** [comment]
@ashpace I looked at it and it seems ok, but I don't get why we can't add it to our main. We actually have a for loop which allows us to test each component.

**Comment by ashpace** [comment]
@GiuseppeMascolo Thank you for the kind words. Please approve and merge my branch

**Pull request merged**
